version: '3'

services:

  erlang:
    image: eddylane/playlist_pal_backend:release-0.0.1
    command: foreground
    environment:
      - MIX_ENV=prod
      - PORT=4000
      - PG_HOST=postgres
      - PG_USERNAME=postgres
      - PG_DATABASE=playlist_pal_prod
      - PG_PASSWORD=postgres
    links:
      - postgres
    depends_on:
      - postgres
    ports:
       - "4000:4000"

  nginx:
    image: eddylane/playlist_pal_frontend:release-0.0.1
    ports:
       - "80:80"

  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=playlist_pal_prod
    ports:
      - "32783:5432"