version: '3'

services:

  elixir:
    build: ./backend
    command: sh -c "mix ecto.setup; mix phx.server"
    environment:
      - MIX_ENV=dev
      - PORT=4000
      - PG_HOST=postgres
      - PG_USERNAME=postgres
      - PG_DATABASE=playlist_pal
      - PG_PASSWORD=postgres
    volumes:
      - ./backend:/app
    ports:
      - "4000:4000"
    links:
      - postgres
    depends_on:
      - postgres

  nginx:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "80:80"

  webpack:
    image: node:6
    command: sh -c "./node_modules/.bin/webpack-dev-server --host 0.0.0.0 --port 4001 --colors"
    volumes:
      - ./frontend:/app
    ports:
     - "4001:4001"
    working_dir: /app

  postgres:
    image: postgres:9.5
    ports:
      - "32783:5432"