version: '3'

services:

  elixir:
    build: ./backend
    command: sh -c "mix ecto.setup; mix phx.server"
    environment:
      - MIX_ENV=dev
      - PORT=4000
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=playlist_pal
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./backend:/app
    ports:
      - "4000:4000"
    links:
      - postgres
    depends_on:
      - postgres

  webpack:
    image: node:6
    command: sh -c "npm rebuild node-sass; ./node_modules/.bin/webpack-dev-server --host 0.0.0.0 --port 80 --colors"
    volumes:
      - ./frontend:/app
    ports:
     - "80:80"
    working_dir: /app

  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=playlist_pal
    ports:
      - "32783:5432"