version: '3'

services:

  elixir:
    build: .
    command: sh -c "mix ecto.setup; mix phoenix.server"
    environment:
      - MIX_ENV=dev
      - PORT=4000
      - PG_HOST=postgres
      - PG_USERNAME=postgres
      - PG_DATABASE=elixir_elm_bootstrap
      - PG_PASSWORD=postgres
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    links:
      - postgres
    depends_on:
      - postgres

  webpack:
    image: node:6
    command: sh -c "./node_modules/.bin/webpack-dev-server --host 0.0.0.0 --port 4001 --colors"
    volumes:
      - .:/app
    ports:
     - "4001:4001"
    working_dir: /app

  postgres:
    image: postgres:9.5
    ports:
      - "5432"