version: '3'

services:

  erlang:
    build:
      context: ./backend
      dockerfile: Dockerfile.release
    command: sh -c "/app/prod/rel/playlist_pal/bin/playlist_pal foreground"
    environment:
      - MIX_ENV=prod
      - PORT=4000
      - PG_HOST=postgres
      - PG_USERNAME=postgres
      - PG_DATABASE=playlist_pal_prod
      - PG_PASSWORD=postgres
    volumes:
      - ./backend/_build:/app
    ports:
      - "4000:4000"
    links:
      - postgres
    depends_on:
      - postgres

  nginx:
    image: nginx:alpine
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
    ports:
      - "80:80"

  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=playlist_pal_prod
    ports:
      - "32783:5432"