version: '3'

services:

  erlang:
    image: eddylane/playlist_pal_backend:release-0.0.1
    command: foreground
    environment:
      - MIX_ENV=prod
      - PORT=4000
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=playlist_pal_prod
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - GUARDIAN_SECRET_KEY=playlist_pal_secret_key
      - SECRET_KEY_BASE=secret_key_base
      - HOST=playlist-pal.local
      - VIRTUAL_HOST=api.playlist-pal.local
      - VIRTUAL_PORT=4000
      - NODE_COOKIE=playlist_pal
    links:
      - postgres
    depends_on:
      - postgres

  nginx:
    image: eddylane/playlist_pal_frontend:release-0.0.1
    environment:
      - API_URL=api.playlist-pal.local
      - CONFIG_VARS=API_URL
      - VIRTUAL_HOST=playlist-pal.local

  proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=playlist_pal_prod
    ports:
      - "32783:5432"